// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: mosque.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMosqueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mosques       *Mosque                `protobuf:"bytes,1,opt,name=mosques,proto3" json:"mosques,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMosqueResponse) Reset() {
	*x = CreateMosqueResponse{}
	mi := &file_mosque_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMosqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMosqueResponse) ProtoMessage() {}

func (x *CreateMosqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mosque_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMosqueResponse.ProtoReflect.Descriptor instead.
func (*CreateMosqueResponse) Descriptor() ([]byte, []int) {
	return file_mosque_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMosqueResponse) GetMosques() *Mosque {
	if x != nil {
		return x.Mosques
	}
	return nil
}

type ListMosquesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMosquesRequest) Reset() {
	*x = ListMosquesRequest{}
	mi := &file_mosque_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMosquesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMosquesRequest) ProtoMessage() {}

func (x *ListMosquesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosque_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMosquesRequest.ProtoReflect.Descriptor instead.
func (*ListMosquesRequest) Descriptor() ([]byte, []int) {
	return file_mosque_proto_rawDescGZIP(), []int{1}
}

type ListMosquesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field name should match the noun "mosque" in the method name.
	// There will be a maximum number of items returned based on the page_size field in the request.
	Mosques       []*Mosque `protobuf:"bytes,1,rep,name=mosques,proto3" json:"mosques,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMosquesResponse) Reset() {
	*x = ListMosquesResponse{}
	mi := &file_mosque_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMosquesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMosquesResponse) ProtoMessage() {}

func (x *ListMosquesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mosque_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMosquesResponse.ProtoReflect.Descriptor instead.
func (*ListMosquesResponse) Descriptor() ([]byte, []int) {
	return file_mosque_proto_rawDescGZIP(), []int{2}
}

func (x *ListMosquesResponse) GetMosques() []*Mosque {
	if x != nil {
		return x.Mosques
	}
	return nil
}

type GetMosqueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field will contain name of the resource requested.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMosqueRequest) Reset() {
	*x = GetMosqueRequest{}
	mi := &file_mosque_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMosqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMosqueRequest) ProtoMessage() {}

func (x *GetMosqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosque_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMosqueRequest.ProtoReflect.Descriptor instead.
func (*GetMosqueRequest) Descriptor() ([]byte, []int) {
	return file_mosque_proto_rawDescGZIP(), []int{3}
}

func (x *GetMosqueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateMosqueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	EidTime       string                 `protobuf:"bytes,3,opt,name=eid_time,json=eidTime,proto3" json:"eid_time,omitempty"`
	JummahTime    string                 `protobuf:"bytes,4,opt,name=jummah_time,json=jummahTime,proto3" json:"jummah_time,omitempty"`
	Lat           float64                `protobuf:"fixed64,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,6,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMosqueRequest) Reset() {
	*x = CreateMosqueRequest{}
	mi := &file_mosque_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMosqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMosqueRequest) ProtoMessage() {}

func (x *CreateMosqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosque_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMosqueRequest.ProtoReflect.Descriptor instead.
func (*CreateMosqueRequest) Descriptor() ([]byte, []int) {
	return file_mosque_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMosqueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMosqueRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateMosqueRequest) GetEidTime() string {
	if x != nil {
		return x.EidTime
	}
	return ""
}

func (x *CreateMosqueRequest) GetJummahTime() string {
	if x != nil {
		return x.JummahTime
	}
	return ""
}

func (x *CreateMosqueRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *CreateMosqueRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type UpdateMosqueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	EidTime       string                 `protobuf:"bytes,4,opt,name=eid_time,json=eidTime,proto3" json:"eid_time,omitempty"`
	JummahTime    string                 `protobuf:"bytes,5,opt,name=jummah_time,json=jummahTime,proto3" json:"jummah_time,omitempty"`
	Lat           float64                `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,7,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMosqueRequest) Reset() {
	*x = UpdateMosqueRequest{}
	mi := &file_mosque_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMosqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMosqueRequest) ProtoMessage() {}

func (x *UpdateMosqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosque_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMosqueRequest.ProtoReflect.Descriptor instead.
func (*UpdateMosqueRequest) Descriptor() ([]byte, []int) {
	return file_mosque_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMosqueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMosqueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMosqueRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateMosqueRequest) GetEidTime() string {
	if x != nil {
		return x.EidTime
	}
	return ""
}

func (x *UpdateMosqueRequest) GetJummahTime() string {
	if x != nil {
		return x.JummahTime
	}
	return ""
}

func (x *UpdateMosqueRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateMosqueRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type UpdateMosqueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field will contain name of the resource requested.
	Mosques       *Mosque `protobuf:"bytes,1,opt,name=mosques,proto3" json:"mosques,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMosqueResponse) Reset() {
	*x = UpdateMosqueResponse{}
	mi := &file_mosque_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMosqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMosqueResponse) ProtoMessage() {}

func (x *UpdateMosqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mosque_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMosqueResponse.ProtoReflect.Descriptor instead.
func (*UpdateMosqueResponse) Descriptor() ([]byte, []int) {
	return file_mosque_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMosqueResponse) GetMosques() *Mosque {
	if x != nil {
		return x.Mosques
	}
	return nil
}

type DeleteMosqueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the mosque to be deleted.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMosqueRequest) Reset() {
	*x = DeleteMosqueRequest{}
	mi := &file_mosque_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMosqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMosqueRequest) ProtoMessage() {}

func (x *DeleteMosqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mosque_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMosqueRequest.ProtoReflect.Descriptor instead.
func (*DeleteMosqueRequest) Descriptor() ([]byte, []int) {
	return file_mosque_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMosqueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_mosque_proto protoreflect.FileDescriptor

const file_mosque_proto_rawDesc = "" +
	"\n" +
	"\fmosque.proto\x12\x06mosque\x1a\vtypes.proto\"?\n" +
	"\x14CreateMosqueResponse\x12'\n" +
	"\amosques\x18\x01 \x01(\v2\r.types.MosqueR\amosques\"\x14\n" +
	"\x12ListMosquesRequest\">\n" +
	"\x13ListMosquesResponse\x12'\n" +
	"\amosques\x18\x01 \x03(\v2\r.types.MosqueR\amosques\"&\n" +
	"\x10GetMosqueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa3\x01\n" +
	"\x13CreateMosqueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\beid_time\x18\x03 \x01(\tR\aeidTime\x12\x1f\n" +
	"\vjummah_time\x18\x04 \x01(\tR\n" +
	"jummahTime\x12\x10\n" +
	"\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x06 \x01(\x01R\x03lng\"\xb3\x01\n" +
	"\x13UpdateMosqueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x19\n" +
	"\beid_time\x18\x04 \x01(\tR\aeidTime\x12\x1f\n" +
	"\vjummah_time\x18\x05 \x01(\tR\n" +
	"jummahTime\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\a \x01(\x01R\x03lng\"?\n" +
	"\x14UpdateMosqueResponse\x12'\n" +
	"\amosques\x18\x01 \x01(\v2\r.types.MosqueR\amosques\")\n" +
	"\x13DeleteMosqueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xed\x01\n" +
	"\rMosqueService\x12I\n" +
	"\fCreateMosque\x12\x1b.mosque.CreateMosqueRequest\x1a\x1c.mosque.CreateMosqueResponse\x12F\n" +
	"\vListMosques\x12\x1a.mosque.ListMosquesRequest\x1a\x1b.mosque.ListMosquesResponse\x12I\n" +
	"\fUpdateMosque\x12\x1b.mosque.UpdateMosqueRequest\x1a\x1c.mosque.UpdateMosqueResponseB-Z+github.com/inidaname/mosque_location/protosb\x06proto3"

var (
	file_mosque_proto_rawDescOnce sync.Once
	file_mosque_proto_rawDescData []byte
)

func file_mosque_proto_rawDescGZIP() []byte {
	file_mosque_proto_rawDescOnce.Do(func() {
		file_mosque_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mosque_proto_rawDesc), len(file_mosque_proto_rawDesc)))
	})
	return file_mosque_proto_rawDescData
}

var file_mosque_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mosque_proto_goTypes = []any{
	(*CreateMosqueResponse)(nil), // 0: mosque.CreateMosqueResponse
	(*ListMosquesRequest)(nil),   // 1: mosque.ListMosquesRequest
	(*ListMosquesResponse)(nil),  // 2: mosque.ListMosquesResponse
	(*GetMosqueRequest)(nil),     // 3: mosque.GetMosqueRequest
	(*CreateMosqueRequest)(nil),  // 4: mosque.CreateMosqueRequest
	(*UpdateMosqueRequest)(nil),  // 5: mosque.UpdateMosqueRequest
	(*UpdateMosqueResponse)(nil), // 6: mosque.UpdateMosqueResponse
	(*DeleteMosqueRequest)(nil),  // 7: mosque.DeleteMosqueRequest
	(*Mosque)(nil),               // 8: types.Mosque
}
var file_mosque_proto_depIdxs = []int32{
	8, // 0: mosque.CreateMosqueResponse.mosques:type_name -> types.Mosque
	8, // 1: mosque.ListMosquesResponse.mosques:type_name -> types.Mosque
	8, // 2: mosque.UpdateMosqueResponse.mosques:type_name -> types.Mosque
	4, // 3: mosque.MosqueService.CreateMosque:input_type -> mosque.CreateMosqueRequest
	1, // 4: mosque.MosqueService.ListMosques:input_type -> mosque.ListMosquesRequest
	5, // 5: mosque.MosqueService.UpdateMosque:input_type -> mosque.UpdateMosqueRequest
	0, // 6: mosque.MosqueService.CreateMosque:output_type -> mosque.CreateMosqueResponse
	2, // 7: mosque.MosqueService.ListMosques:output_type -> mosque.ListMosquesResponse
	6, // 8: mosque.MosqueService.UpdateMosque:output_type -> mosque.UpdateMosqueResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mosque_proto_init() }
func file_mosque_proto_init() {
	if File_mosque_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mosque_proto_rawDesc), len(file_mosque_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mosque_proto_goTypes,
		DependencyIndexes: file_mosque_proto_depIdxs,
		MessageInfos:      file_mosque_proto_msgTypes,
	}.Build()
	File_mosque_proto = out.File
	file_mosque_proto_goTypes = nil
	file_mosque_proto_depIdxs = nil
}
